# Generated by Django 4.1.5 on 2023-01-07 19:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("food_module", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfooditem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userfooditem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
