# Generated by Django 4.1.5 on 2023-01-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_module", "0003_reciperecommendation_calories_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reciperecommendation",
            name="steps",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
