# Generated by Django 4.1.5 on 2023-01-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_module", "0005_remove_reciperecommendation_carbohydrates_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="expiry_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
