# Generated by Django 4.1.5 on 2023-02-06 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("food_module", "0006_fooditem_expiry_time"),
        ("food_module", "0007_reciperecommendation_carbohydrates_and_more"),
        ("food_module", "0008_reciperecommendation_time_to_make"),
        (
            "food_module",
            "0009_userfooditem_is_stale_alter_fooditem_expiry_time_and_more",
        ),
    ]

    dependencies = [
        ("food_module", "0005_remove_reciperecommendation_carbohydrates_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reciperecommendation",
            name="carbohydrates",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reciperecommendation",
            name="saturated_fat",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reciperecommendation",
            name="time_to_make",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userfooditem",
            name="is_stale",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="expiry_time",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reciperecommendation",
            name="steps",
            field=models.CharField(blank=True, max_length=10024, null=True),
        ),
        migrations.RemoveField(
            model_name="userfooditem",
            name="food_item",
        ),
        migrations.AddField(
            model_name="userfooditem",
            name="food_item",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="food_module.fooditem",
            ),
            preserve_default=False,
        ),
    ]
