# Generated by Django 4.1.5 on 2023-01-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_module", "0006_fooditem_expiry_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="reciperecommendation",
            name="carbohydrates",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reciperecommendation",
            name="saturated_fat",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
