# Generated by Django 4.1.5 on 2023-01-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_module", "0007_reciperecommendation_carbohydrates_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reciperecommendation",
            name="time_to_make",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
