version: '3.0'

services:
  ml:
    build: ml
    restart: always
    ports:
      - 8081:8000
    networks:
      - web
  backend:
    build: backend
    restart: always
    ports:
      - 8082:8000
    networks:
      - web
  nginx:
    image: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - web

networks:
  web:
    driver: bridge
