# Generated by Django 4.1.5 on 2023-01-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware_module", "0003_opencount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opencount",
            name="count",
            field=models.IntegerField(default=1),
        ),
    ]
