# Generated by Django 4.1.3 on 2022-11-29 23:36

from django.db import migrations
import user_module.models


class Migration(migrations.Migration):

    dependencies = [
        ("user_module", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", user_module.models.UserManager()),
            ],
        ),
    ]
