# Generated by Django 4.1.5 on 2023-01-11 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_module", "0005_remove_customuser_username_alter_customuser_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserNotification",
            fields=[
                (
                    "timestampedmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="user_module.timestampedmodel",
                    ),
                ),
                ("notification_title", models.CharField(max_length=255)),
                ("notification_body", models.CharField(max_length=255)),
                (
                    "notification_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="notifications/images/"
                    ),
                ),
                ("notification_url", models.URLField(blank=True, null=True)),
                ("read", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=("user_module.timestampedmodel",),
        ),
    ]
