# Generated by Django 4.1.7 on 2023-04-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0006_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='uid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
