# Generated by Django 4.1.6 on 2023-03-28 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0007_customuser_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='uid',
        ),
    ]
