# Generated by Django 4.1.6 on 2023-03-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0008_remove_customuser_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='uid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
