# Generated by Django 4.1.7 on 2023-04-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_module', '0006_fooditem_expiry_time_squashed_0009_userfooditem_is_stale_alter_fooditem_expiry_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciperecommendation',
            name='recipe_image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_images'),
        ),
        migrations.AddField(
            model_name='reciperecommendation',
            name='recipe_video_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
