# Generated by Django 4.1.7 on 2023-04-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_module', '0010_reciperecommendation_recipe_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciperecommendation',
            name='recipe_image',
        ),
        migrations.AddField(
            model_name='reciperecommendation',
            name='recipe_image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
