# Generated by Django 4.1.6 on 2023-03-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware_module', '0004_alter_opencount_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_identified',
            field=models.ImageField(default=None, upload_to='hardware_images_identified/'),
        ),
    ]
